version: '3.8'
services:
  web:
    build: ./resordsys
    ports:
      - "80:80"
  api:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: run.py
      FLASK_RUN_HOST: 0.0.0.0
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/var/lib/mysql
