version: '3.9'

services:
  web:
    build: ./resordsys
    networks:
      - backend_network
    ports:
      - "80:80"
  
  api:
    build: ./backend
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - backend_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sisyphus
      MYSQL_DATABASE: restaurant
      MYSQL_ROOT_HOST: '%'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    networks:
      - backend_network
    volumes:
      - ./mydata:/var/lib/mysql
      - ./restaurant.sql:/docker-entrypoint-initdb.d/restaurant.sql
      - ./authentication.sql:/docker-entrypoint-initdb.d/authentication.sql

networks:
  backend_network:
    driver: bridge

volumes:
  dbdata:
